// Code generated by ogen, DO NOT EDIT.

package sp

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Auth implements auth operation.
//
// Auth.
//
// GET /auth
func (UnimplementedHandler) Auth(ctx context.Context) (r AuthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Callback implements callback operation.
//
// Callback.
//
// GET /callback
func (UnimplementedHandler) Callback(ctx context.Context, params CallbackParams) (r CallbackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Index implements index operation.
//
// Index.
//
// GET /
func (UnimplementedHandler) Index(ctx context.Context) (r IndexRes, _ error) {
	return r, ht.ErrNotImplemented
}
