// Code generated by ogen, DO NOT EDIT.

package rp

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Begin implements begin operation.
//
// Begin.
//
// GET /auth
func (UnimplementedHandler) Begin(ctx context.Context, params BeginParams) (r BeginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Callback implements callback operation.
//
// Callback.
//
// GET /callback
func (UnimplementedHandler) Callback(ctx context.Context, params CallbackParams) (r CallbackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// End implements end operation.
//
// End.
//
// POST /auth
func (UnimplementedHandler) End(ctx context.Context, req *EndReq) (r EndRes, _ error) {
	return r, ht.ErrNotImplemented
}
